on: [push, pull_request]

jobs:
  bundle:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install briefcase requests
      - name: Just support
        run: |
          sudo apt-get install -y python3-cffi libffi-dev

          ldconfig -p | grep libffi
          python download.py
          tar -xzf support.tar.gz
          bin/python3 --version
          echo $LD_LIBRARY_PATH
          bin/python3 -c "import os; print(os.environ.get('LD_LIBRARY_PATH'))"
          echo hi
          ldd /lib/python3.8/lib-dynload/_ctypes*
          bin/python3 -c "import ctypes"
      # - name: Make Bundle
      #   run: |
      #     briefcase create
      #     briefcase build
      #     briefcase package
      #     briefcase run
      #     mkdir -p ${{ github.workspace }}/artifact
      #     mv ${{ env.output }} ${{ github.workspace }}/artifact
      # - name: Upload Artifact
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: hellobriefcase-${{ github.sha }}
      #     path: artifact/

