on: [push, pull_request]

jobs:
  bundle:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install briefcase requests
      - name: Just support
        run: |
          python download.py
          tar -xzf support.tar.gz
          bin/python3 --version
          bin/python3 -c "import ctypes"